name: Torch
favicon: null
layout_spectrum: 0.74568
typography_spectrum: 0.25816
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f3f3'
    - '#000000'
    - '#9d9d9d'
    - '#3d3d3d'
    - '#696969'
  brandStrength: 0.625
  lightness: 0.000653969356790185
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
